# Generated by Django 5.1.1 on 2025-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='articul',
            field=models.CharField(max_length=7, unique=True, verbose_name='art'),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='articul',
            field=models.CharField(max_length=7, unique=True, verbose_name='art'),
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='articul',
            field=models.CharField(max_length=7, unique=True, verbose_name='art'),
        ),
    ]
